name: ghostferry

up:
  - homebrew:
    - glide
    - mysql
  - ruby: 2.5.1
  - bundler:
      gemfile: test/integration/Gemfile
  - go:
      version: 1.10.3
  - custom:
      name: Docker for Mac
      met?: test -e /Applications/Docker.app
      meet: echo "Docker not found. Install from https://docs.docker.com/docker-for-mac/"; false
  - custom:
      name: Go Dependencies
      met?: dep ensure
      meet: echo 'dep failed to ensure dependencies'; false
  - custom:
      name: MySQL
      met?: docker-compose up -d mysql-1 mysql-2
      meet: echo 'mysql failed to start'; false
      down: docker-compose stop mysql-1 mysql-2

commands:
  test:
    desc: Run the test suite.
    run: make test
